name: GitHub Actions Check
run-name: ${{ github.actor }} Checks 🚀
on: [push, pull_request]
jobs:
  Link-Format-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/link-format-chk.sh
  Build-Table-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/buildtable.pl >/tmp/table.mediawiki || exit 1
  Diff-Checks:
    name: "Diff Checks (fails until number assignment)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: scripts/diffcheck.sh
  Typo-Checks:
    name: "Typo Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master

  BIP340-Test-Vectors:
    name: "BIP340 Test Vector Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run vector consistency check
        run: python3 bip-0340/check_vectors.py
